# Generated by Django 3.0.5 on 2020-04-28 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

 
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.TextField(verbose_name='全球唯一图书编号')),
                ('title', models.TextField(verbose_name='书名')),
                ('author', models.TextField(verbose_name='作者')),
                ('author_intro', models.TextField(verbose_name='作者简介')),
                ('tag', models.TextField(verbose_name='标签')),
                ('NumRaters', models.IntegerField(default=0, verbose_name='评分人数')),
                ('average', models.FloatField(default=0.0, verbose_name='平均评分')),
                ('Id', models.TextField(default='', primary_key=True, serialize=False, verbose_name='豆瓣图书Id')),
                ('binding', models.TextField(verbose_name='精装/简装')),
                ('pages', models.IntegerField(default=0, verbose_name='页数')),
                ('publisher', models.TextField(verbose_name='出版商')),
                ('origin_title', models.TextField(verbose_name='图书原名')),
                ('url', models.TextField(verbose_name='豆瓣链接')),
                ('image', models.TextField(verbose_name='图书豆瓣图片')),
                ('summary', models.TextField(verbose_name='图书概述')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ManyToManyField(blank=True, related_name='cart_user_profile', to='store.Book', verbose_name='购物车')),
                ('purchased', models.ManyToManyField(blank=True, related_name='purchased_user_profile', to='store.Book', verbose_name='已购买商品')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
