# Generated by Django 3.0.5 on 2020-04-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [ 
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=19.99, max_digits=8, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='book',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
